name: Deploy Forge App

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  workflow_dispatch:    # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Setup Forge CLI
        run: |
          npm install -g @forge/cli
          forge settings set usage-analytics true

      - name: Deploying Forge App
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        run: forge deploy
